package com.cluster.employeeproject.entity;

// Generated Feb 28, 2013 3:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.cluster.employeeproject.common.entity.BaseDO;

/**
 * AddressType generated by hbm2java
 */
@Entity
@Table(name = "ADDRESS_TYPE", schema = "employeeproject")
public class AddressType extends BaseDO implements java.io.Serializable {

	private long addressTypeId;
	private String addressType;
	private Set<EmployeeAddress> employeeAddresses = new HashSet<EmployeeAddress>(
			0);

	public AddressType() {
	}

	public AddressType(long addressTypeId) {
		this.addressTypeId = addressTypeId;
	}

	public AddressType(long addressTypeId, String addressType,
			Set<EmployeeAddress> employeeAddresses) {
		this.addressTypeId = addressTypeId;
		this.addressType = addressType;
		this.employeeAddresses = employeeAddresses;
	}

	@Id
	@Column(name = "ADDRESS_TYPE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	/*@GeneratedValue(generator="ADDRESS_TYPE")
	@SequenceGenerator(name="ADDRESS_TYPE",sequenceName="ADDRESS_TYPE_SEQ")*/
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getAddressTypeId() {
		return this.addressTypeId;
	}

	public void setAddressTypeId(long addressTypeId) {
		this.addressTypeId = addressTypeId;
	}

	@Column(name = "ADDRESS_TYPE", length = 50)
	public String getAddressType() {
		return this.addressType;
	}

	public void setAddressType(String addressType) {
		this.addressType = addressType;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "addressType",cascade=CascadeType.ALL)
	public Set<EmployeeAddress> getEmployeeAddresses() {
		return this.employeeAddresses;
	}

	public void setEmployeeAddresses(Set<EmployeeAddress> employeeAddresses) {
		this.employeeAddresses = employeeAddresses;
	}

}
