package com.cluster.employeeproject.entity;

// Generated Feb 28, 2013 3:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.cluster.employeeproject.common.entity.BaseDO;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "COUNTRY", schema = "employeeproject")
public class Country  extends BaseDO implements java.io.Serializable {

	private long countryId;
	private String countryName;
	private Set<State> states = new HashSet<State>(0);

	public Country() {
	}

	public Country(long countryId) {
		this.countryId = countryId;
	}

	public Country(long countryId, String countryName, Set<State> states) {
		this.countryId = countryId;
		this.countryName = countryName;
		this.states = states;
	}

	@Id
	@Column(name = "COUNTRY_ID", unique = true, nullable = false, precision = 22, scale = 0)
	/*@SequenceGenerator(name = "country",sequenceName="COUNTRY_SEQ")
	@GeneratedValue(generator="country")*/
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getCountryId() {
		return this.countryId;
	}

	public void setCountryId(long countryId) {
		this.countryId = countryId;
	}

	@Column(name = "COUNTRY_NAME", length = 50)
	public String getCountryName() {
		return this.countryName;
	}

	public void setCountryName(String countryName) {
		this.countryName = countryName;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country",cascade=CascadeType.ALL)
	public Set<State> getStates() {
		return this.states;
	}

	public void setStates(Set<State> states) {
		this.states = states;
	}

}
