package com.cluster.employeeproject.entity;

// Generated Feb 28, 2013 3:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.cluster.employeeproject.common.entity.BaseDO;

/**
 * Department generated by hbm2java
 */
@Entity
@Table(name = "DEPARTMENT", schema = "employeeproject")
public class Department extends BaseDO implements java.io.Serializable {

	private long departmentId;
	private String departmentName;
	private Set<Employee> employees = new HashSet<Employee>(0);

	public Department() {
	}

	public Department(long departmentId) {
		this.departmentId = departmentId;
	}

	public Department(long departmentId, String departmentName,
			Set<Employee> employees) {
		this.departmentId = departmentId;
		this.departmentName = departmentName;
		this.employees = employees;
	}

	@Id
	@Column(name = "DEPARTMENT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	/*@GeneratedValue(generator="department")
	@SequenceGenerator(name="department", sequenceName="DEPARTMENT_SEQ")*/
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getDepartmentId() {
		return this.departmentId;
	}

	public void setDepartmentId(long departmentId) {
		this.departmentId = departmentId;
	}

	@Column(name = "DEPARTMENT_NAME", length = 50)
	public String getDepartmentName() {
		return this.departmentName;
	}

	public void setDepartmentName(String departmentName) {
		this.departmentName = departmentName;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "department",cascade=CascadeType.ALL)
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
