package com.cluster.employeeproject.entity;

// Generated Feb 28, 2013 3:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

import com.cluster.employeeproject.common.entity.BaseDO;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "ROLE", schema = "employeeproject")
public class Role extends BaseDO implements java.io.Serializable {

	private long roleId;
	private Status status;
	private String roleType;
	private Set<Security> securities = new HashSet<Security>(0);
	private Set<EmployeeRole> employeeRoles = new HashSet<EmployeeRole>(0);

	public Role() {
	}

	public Role(long roleId) {
		this.roleId = roleId;
	}

	public Role(long roleId, Status status, String roleType,
			Set<Security> securities, Set<EmployeeRole> employeeRoles) {
		this.roleId = roleId;
		this.status = status;
		this.roleType = roleType;
		this.securities = securities;
		this.employeeRoles = employeeRoles;
	}

	@Id
	@Column(name = "ROLE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getRoleId() {
		return this.roleId;
	}

	public void setRoleId(long roleId) {
		this.roleId = roleId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "STATUS_ID")
	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	@Column(name = "ROLE_TYPE", length = 50)
	public String getRoleType() {
		return this.roleType;
	}

	public void setRoleType(String roleType) {
		this.roleType = roleType;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "role",cascade=CascadeType.ALL)
	public Set<Security> getSecurities() {
		return this.securities;
	}

	public void setSecurities(Set<Security> securities) {
		this.securities = securities;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "role")
	public Set<EmployeeRole> getEmployeeRoles() {
		return this.employeeRoles;
	}

	public void setEmployeeRoles(Set<EmployeeRole> employeeRoles) {
		this.employeeRoles = employeeRoles;
	}

}
