package com.cluster.employeeproject.entity;

// Generated Feb 28, 2013 3:50:08 PM by Hibernate Tools 3.4.0.CR1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.cluster.employeeproject.common.entity.BaseDO;

/**
 * Security generated by hbm2java
 */
@Entity
@Table(name = "SECURITY", schema = "employeeproject")
public class Security extends BaseDO implements java.io.Serializable {

	private long securityId;
	private Role role;
	private String application;

	public Security() {
	}

	public Security(long securityId) {
		this.securityId = securityId;
	}

	public Security(long securityId, Role role, String application) {
		this.securityId = securityId;
		this.role = role;
		this.application = application;
	}

	@Id
	@Column(name = "SECURITY_ID", unique = true, nullable = false, precision = 22, scale = 0)
/*	@SequenceGenerator(name="security", sequenceName="SECURITY_SEQ")
	@GeneratedValue(generator="security")*/
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getSecurityId() {
		return this.securityId;
	}

	public void setSecurityId(long securityId) {
		this.securityId = securityId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "ROLE_ID")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

	@Column(name = "APPLICATION", length = 200)
	public String getApplication() {
		return this.application;
	}

	public void setApplication(String application) {
		this.application = application;
	}

}
