package com.cluster.employeeproject.entity;

// Generated Feb 28, 2013 3:50:08 PM by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.cluster.employeeproject.common.entity.BaseDO;

/**
 * State generated by hbm2java
 */
@Entity
@Table(name = "STATE", schema = "employeeproject")
public class State extends BaseDO implements java.io.Serializable {

	private long stateId;
	private Country country;
	private String stateName;
	private Set<City> cities = new HashSet<City>(0);

	public State() {
	}

	public State(long stateId) {
		this.stateId = stateId;
	}

	public State(long stateId, Country country, String stateName,
			Set<City> cities) {
		this.stateId = stateId;
		this.country = country;
		this.stateName = stateName;
		this.cities = cities;
	}

	@Id
	@Column(name = "STATE_ID", unique = true, nullable = false, precision = 22, scale = 0)
	/*@SequenceGenerator(name="STATE_STATEID_GENERATOR", sequenceName="STATE_SEQ")
	@GeneratedValue(generator="STATE_STATEID_GENERATOR")*/
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getStateId() {
		return this.stateId;
	}

	public void setStateId(long stateId) {
		this.stateId = stateId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "COUNTRY_ID")
	public Country getCountry() {
		return this.country;
	}

	public void setCountry(Country country) {
		this.country = country;
	}

	@Column(name = "STATE_NAME", length = 50)
	public String getStateName() {
		return this.stateName;
	}

	public void setStateName(String stateName) {
		this.stateName = stateName;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "state",cascade=CascadeType.ALL)
	public Set<City> getCities() {
		return this.cities;
	}

	public void setCities(Set<City> cities) {
		this.cities = cities;
	}

}
