package com.cluster.employeeproject.entity;

// Generated Feb 28, 2013 3:50:08 PM by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.SequenceGenerator;
import javax.persistence.Table;

import com.cluster.employeeproject.common.entity.BaseDO;

/**
 * Status generated by hbm2java
 */
@Entity
@Table(name = "STATUS", schema = "employeeproject")
public class Status extends BaseDO  implements java.io.Serializable {

	private long statusId;
	private String status;
	private Set<Role> roles = new HashSet<Role>(0);
	private Set<EmployeeRole> employeeRoles = new HashSet<EmployeeRole>(0);
	private Set<Employee> employees = new HashSet<Employee>(0);

	public Status() {
	}

	public Status(long statusId) {
		this.statusId = statusId;
	}

	public Status(long statusId, String status, Set<Role> roles,
			Set<EmployeeRole> employeeRoles, Set<Employee> employees) {
		this.statusId = statusId;
		this.status = status;
		this.roles = roles;
		this.employeeRoles = employeeRoles;
		this.employees = employees;
	}

	@Id
	@Column(name = "STATUS_ID", unique = true, nullable = false, precision = 22, scale = 0)
	/*@SequenceGenerator(name="STATUS_STATUSID_GENERATOR", sequenceName="STATUS_SEQ")
	@GeneratedValue(generator="STATUS_STATUSID_GENERATOR")*/
	@GeneratedValue(strategy=GenerationType.AUTO)
	public long getStatusId() {
		return this.statusId;
	}

	public void setStatusId(long statusId) {
		this.statusId = statusId;
	}

	@Column(name = "STATUS", length = 50)
	public String getStatus() {
		return this.status;
	}

	public void setStatus(String status) {
		this.status = status;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "status",cascade=CascadeType.ALL)
	public Set<Role> getRoles() {
		return this.roles;
	}

	public void setRoles(Set<Role> roles) {
		this.roles = roles;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "status",cascade=CascadeType.ALL)
	public Set<EmployeeRole> getEmployeeRoles() {
		return this.employeeRoles;
	}

	public void setEmployeeRoles(Set<EmployeeRole> employeeRoles) {
		this.employeeRoles = employeeRoles;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "status",cascade=CascadeType.ALL)
	public Set<Employee> getEmployees() {
		return this.employees;
	}

	public void setEmployees(Set<Employee> employees) {
		this.employees = employees;
	}

}
